from functools import lru_cache
import heapq

# Keypad Layouts
NUM_KEYPAD = {
    '7': (0, 0), '8': (0, 1), '9': (0, 2),
    '4': (1, 0), '5': (1, 1), '6': (1, 2),
    '1': (2, 0), '2': (2, 1), '3': (2, 2),
                 '0': (3, 1), 'A': (3, 2)
}
NUM_GAP = (3, 0)

DIR_KEYPAD = {
                 '^': (0, 1), 'A': (0, 2),
    '<': (1, 0), 'v': (1, 1), '>': (1, 2)
}
DIR_GAP = (0, 0)

def get_sequences(start_pos, end_pos, gap_pos):
    """
    Returns all shortest valid sequences of moves from start_pos to end_pos
    avoiding the gap_pos.
    """
    sr, sc = start_pos
    er, ec = end_pos
    dr, dc = er - sr, ec - sc
    
    moves = []
    if dr > 0: moves.extend(['v'] * abs(dr))
    elif dr < 0: moves.extend(['^'] * abs(dr))
    if dc > 0: moves.extend(['>'] * abs(dc))
    elif dc < 0: moves.extend(['<'] * abs(dc))
    
    # Simple permutations isn't enough because some might hit the gap.
    # We only care about L-shapes mostly (move all V then all H, or all H then all V).
    # Actually, minimizing turns is usually optimal for the NEXT robot level, 
    # but strictly speaking any shortest Manhattan path is a candidate.
    # However, for these small grids, the only constraints are hitting the gap.
    # Since we want to MINIMIZE the cost at the next level, grouping keys is good (e.g. >>^^ is better than >^>^).
    # So we essentially only consider permutations that don't switch back and forth needlessly.
    # i.e., permutations of the moves list.
    
    from itertools import permutations
    
    valid_seqs = set()
    for p in set(permutations(moves)):
        # Check if hitting gap
        cr, cc = sr, sc
        valid = True
        for move in p:
            if move == '^': cr -= 1
            elif move == 'v': cr += 1
            elif move == '<': cc -= 1
            elif move == '>': cc += 1
            
            if (cr, cc) == gap_pos:
                valid = False
                break
        
        if valid:
            valid_seqs.add("".join(p) + "A")
            
    return list(valid_seqs)

@lru_cache(None)
def solve_pair(start_char, end_char, depth):
    # Depth 0: Me typing on my directional keypad.
    # Depth N: Robot N typing on keypad for Robot N-1.
    
    # If depth 0, we are at the top level (human).
    # Wait, problem says "One directional keypad that you are using."
    # Then "Two directional keypads that robots are using."
    # Then "One numeric keypad".
    # Hierarchy:
    # Me -> DirPad3 (Robot 2) -> DirPad2 (Robot 1) -> NumPad (Door)
    # The example says: "There are multiple shortest possible sequences... of directional keypad button presses that would cause this robot to tell the first robot to type 029A"
    # Actually, let's map the layers:
    # Layer 0: Numeric Keypad (Goal)
    # Layer 1: Robot 1 (DirPad) controlling Layer 0
    # Layer 2: Robot 2 (DirPad) controlling Layer 1
    # Layer 3: Me (DirPad) controlling Layer 2
    
    # Wait, the problem asks for "fewest number of button presses you'll need to perform" (Layer 3 length).
    # The complexity is length * numeric_part.
    
    # So we need a recursive function `min_cost(seq, layer)`.
    # layer 0 is Numeric.
    # layer > 0 is Directional.
    # How many directional layers? "Two directional keypads that robots are using."
    # So: Me -> Robot2 -> Robot1 -> NumPad
    # Total 2 robots. So 2 intermediate layers + Me.
    # Actually, generally:
    # Target is generated by Robot 1.
    # Robot 1 commands are generated by Robot 2.
    # Robot 2 commands are generated by Me.
    
    # Let's verify depths:
    # To type on NumPad (Layer 0), we need moves on DirPad (Layer 1).
    # To type on DirPad (Layer 1), we need moves on DirPad (Layer 2).
    # To type on DirPad (Layer 2), we need moves on DirPad (Layer 3 - Me).
    
    # Recursion:
    # To move from '0' to '2' on NumPad (Layer 0), we need a sequence on Layer 1 (e.g. "^A").
    # We want the sequence on Layer 1 that minimizes the cost on Layer 2.
    
    # Actually, we can just say:
    # `total_robots = 2`.
    # `get_cost(u, v, depth)` returns length of sequence at `depth` to move u->v at `depth-1`.
    
    # If depth == 0 (Me): I press the buttons directly. The cost is 1 per button sequence length?
    # No, if I need to move from A to <, I type just that.
    # Wait, "cost" usually means length of the final string I type.
    # So at depth 0 (Me), moving u->v is just 1 button press?
    # No, I am typing the sequence.
    # Let's say:
    # `min_len(seq, keypad_type, robots_above)`
    
    # Let's stick to the mapping:
    # Level 0: Numeric Keypad.
    # Level 1: DirPad (Robot 1).
    # Level 2: DirPad (Robot 2).
    # Level 3: Me.
    
    # We want length at Level 3.
    # `solve_seq(seq, 0)` returns len at 3.
    pass

# We need a unified solve function
@lru_cache(None)
def min_cost(u, v, depth):
    # depth represents the number of robotic layers ON TOP of the current keypad.
    # If depth == 0, we are at the top layer (Me). I explicitly type the move, so length is 1 for the move itself?
    # No, `min_cost(u, v, depth)` should return the length of the string I type 
    # to make the robot at `current_layer` move from u to v and press A.
    
    # Let's define depth:
    # Depth = 0: The sequence is typed by ME directly. The length is `len(path)`.
    # Depth > 0: The sequence `path` must be typed by a robot. We need to find cost to type `path`.
    
    # Keypad handling: 
    # If we are resolving moves for the Numeric Keypad, we generate paths on NumPad.
    # Those paths are symbols on DirPad.
    # We calculate cost of those symbols with `depth-1` robots?
    
    # Let's parameterize by (keypad_type, robots_left).
    # But `keypad_type` is implied by the symbols? NumPad has digits, DirPad has arrows.
    # Actually, all layers except the bottom one are DirPads.
    
    # Standard approach:
    # `solve(sequence, depth)`: returns cost to type `sequence` given `depth` robots above it.
    # If depth == 0: return len(sequence).
    
    # But we need to handle the transitions (u->v).
    # `cost_pair(u, v, depth)`: cost to move from u to v and press A.
    
    pass

# Refined Logic
GAP_POS = {
    'num': NUM_GAP,
    'dir': DIR_GAP
}
KEYPADS = {
    'num': NUM_KEYPAD,
    'dir': DIR_KEYPAD
}

@lru_cache(None)
def get_path_cost(start_key, end_key, depth, is_num_pad):
    # Get layout
    keypad = KEYPADS['num'] if is_num_pad else KEYPADS['dir']
    gap = GAP_POS['num'] if is_num_pad else GAP_POS['dir']
    
    start_pos = keypad[start_key]
    end_pos = keypad[end_key]
    
    paths = get_sequences(start_pos, end_pos, gap)
    
    if depth == 0:
        # Base case: I am typing this path.
        # Shortest path is just the length of the shortest permutation.
        # Since permutations are just reorderings, they all have same length.
        return len(paths[0])
    
    # Recursive step
    # We want to minimize the cost of typing 'path' at the NEXT layer (depth-1).
    # Next layer is ALWAYS a DirPad (robots control robots).
    
    best_cost = float('inf')
    for path in paths:
        # Cost of this path is the sum of costs of moving between its chars
        # The robot playing this path starts at 'A'.
        current_cost = 0
        current_key = 'A'
        for char in path:
            current_cost += get_path_cost(current_key, char, depth - 1, False)
            current_key = char
        best_cost = min(best_cost, current_cost)
        
    return best_cost

def solve_code(code, num_robots=2):
    # Code is on NumPad.
    # Layer structure:
    # -1: Me (typing on Robot N's keypad)
    # 0..N-1: Robots (DirPads)
    # N: NumPad (Goal)
    
    # My recursion `depth` definition:
    # `depth` is number of DirPad robots involved in the chain "above" the current keypad.
    
    # For NumPad moves:
    # We generate paths (e.g. "<A"). These are typed on Robot 1's DirPad.
    # Robot 1 is controlled by Robot 2.
    # Robot 2 is controlled by Me.
    # So `depth` for NumPad moves = 2 (Robot 1, Robot 2). The symbols need to go through 2 layers of translation.
    
    # Wait, simple counting:
    # Target: NumPad.
    # Controller 1: DirPad (Robot 1).
    # Controller 2: DirPad (Robot 2).
    # Controller 3: Me.
    
    # Call `get_path_cost(u, v, depth=2, is_num_pad=True)`?
    # If depth=2:
    #   Path on NumPad -> Seq of DirPad chars.
    #   Recursive call `get_path_cost(..., depth=1, is_num_pad=False)`
    #     Path on DirPad -> Seq of DirPad chars.
    #     Recursive call `get_path_cost(..., depth=0, is_num_pad=False)`
    #       Path on DirPad -> I type it. Cost = len.
    
    # Correct. Depth = Number of robots.
    
    total_cost = 0
    current_key = 'A'
    for char in code:
        total_cost += get_path_cost(current_key, char, num_robots, True)
        current_key = char
        
    numeric_part = int(code[:-1].lstrip('0') or '0') # remove 'A', parse int
    return total_cost * numeric_part

def solve():
    # Example Codes
    codes = ["029A", "980A", "179A", "456A", "379A"]
    total_complexity = 0
    
    print("--- Example Verification ---")
    for code in codes:
        complexity = solve_code(code, num_robots=2)
        cost = solve_code(code, num_robots=2) // int(code[:-1].lstrip('0') or '0')
        print(f"{code}: Cost {cost}, Complexity {complexity}")
        total_complexity += complexity
        
    print(f"Total Example Complexity: {total_complexity}")
    assert total_complexity == 126384, f"Expected 126384, got {total_complexity}"
    
    # Real Input
    try:
        with open('input-day21.txt', 'r') as f:
            real_codes = [line.strip() for line in f if line.strip()]
        
        real_total = 0
        part2_total = 0
        for code in real_codes:
            real_total += solve_code(code, num_robots=2)
            part2_total += solve_code(code, num_robots=25)
            
        print(f"\nPart 1 Final: {real_total}")
        print(f"Part 2 Final: {part2_total}")
        
    except FileNotFoundError:
        print("input-day21.txt not found.")

if __name__ == '__main__':
    solve()
