// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetCommodityCommoditiesTickerGetData, GetCommodityCommoditiesTickerGetErrors, GetCommodityCommoditiesTickerGetResponses, ListCommoditiesCommoditiesGetData, ListCommoditiesCommoditiesGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Commodities
 *
 * 获取全球大宗商品实时报价。
 * 数据来源: yfinance (Yahoo Finance)
 * 缓存策略: 5分钟更新一次，失败时从本地持久化缓存读取。
 */
export const listCommoditiesCommoditiesGet = <ThrowOnError extends boolean = false>(options?: Options<ListCommoditiesCommoditiesGetData, ThrowOnError>) => (options?.client ?? client).get<ListCommoditiesCommoditiesGetResponses, unknown, ThrowOnError>({ url: '/commodities', ...options });

/**
 * Get Commodity
 *
 * 获取单品详情报价。
 */
export const getCommodityCommoditiesTickerGet = <ThrowOnError extends boolean = false>(options: Options<GetCommodityCommoditiesTickerGetData, ThrowOnError>) => (options.client ?? client).get<GetCommodityCommoditiesTickerGetResponses, GetCommodityCommoditiesTickerGetErrors, ThrowOnError>({ url: '/commodities/{ticker}', ...options });
