// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Commodity
 */
export type Commodity = {
    /**
     * Ticker
     *
     * 商品代码
     */
    ticker: string;
    /**
     * Name
     *
     * 商品全称
     */
    name: string;
    /**
     * Price
     *
     * 当前价格
     */
    price: number;
    /**
     * Unit
     *
     * 计价单位 (如 oz, bbl)
     */
    unit: string;
    /**
     * Change Pct
     *
     * 当日涨跌幅 (%)
     */
    change_pct: number;
    /**
     * Change Abs
     *
     * 当日涨跌绝对值
     */
    change_abs: number;
    /**
     * Category
     *
     * 分类 (如 Precious Metals, Energy)
     */
    category: string;
    /**
     * Icon
     *
     * 图标名称 (Lucide)
     */
    icon?: string;
    /**
     * Trend
     *
     * 市场情绪 (Bullish, Bearish, Neutral)
     */
    trend?: string;
    /**
     * Last Updated
     *
     * 上次更新时间 (YYYY-MM-DD HH:MM:SS)
     */
    last_updated: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListCommoditiesCommoditiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/commodities';
};

export type ListCommoditiesCommoditiesGetResponses = {
    /**
     * Response List Commodities Commodities Get
     *
     * Successful Response
     */
    200: Array<Commodity>;
};

export type ListCommoditiesCommoditiesGetResponse = ListCommoditiesCommoditiesGetResponses[keyof ListCommoditiesCommoditiesGetResponses];

export type GetCommodityCommoditiesTickerGetData = {
    body?: never;
    path: {
        /**
         * Ticker
         */
        ticker: string;
    };
    query?: never;
    url: '/commodities/{ticker}';
};

export type GetCommodityCommoditiesTickerGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCommodityCommoditiesTickerGetError = GetCommodityCommoditiesTickerGetErrors[keyof GetCommodityCommoditiesTickerGetErrors];

export type GetCommodityCommoditiesTickerGetResponses = {
    /**
     * Successful Response
     */
    200: Commodity;
};

export type GetCommodityCommoditiesTickerGetResponse = GetCommodityCommoditiesTickerGetResponses[keyof GetCommodityCommoditiesTickerGetResponses];
